apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: registry.digitalocean.com/bontaregistry/front:latest
          name: front
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: front
  type: LoadBalancer
