apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hr
  name: hr-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr
  template:
    metadata:
      labels:
        app: hr
    spec:
      containers:
        - image: registry.digitalocean.com/bontaregistry/hr:latest
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: hr
  type: LoadBalancer
