apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init.js: |
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongo-statefulset-0.mongo-service:27017" },
        { _id: 1, host: "mongo-statefulset-1.mongo-service:27017" },
        { _id: 2, host: "mongo-statefulset-2.mongo-service:27017" }
      ]
    })
