apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: "mongo-service"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        command: ["/bin/sh", "-c"]
        args:
        - >
          mongod --replSet rs0 --bind_ip_all;
          sleep 10;
          if [ $(hostname) = "mongo-statefulset-0" ]; then
            mongosh < /docker-entrypoint-initdb.d/init.js;
          fi;
          tail -f /dev/null;
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: init-script
        configMap:
          name: mongo-init-script
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
